FROM python:3.10-slim

WORKDIR /workspace/backend

RUN apt-get update && \
    apt-get install -y git curl build-essential libgl1-mesa-glx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/workspace

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /workspace/backend

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]